# Generated by Django 6.0 on 2026-01-03 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='newspost',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
