# Generated by Django 6.0 on 2025-12-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, max_length=300)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(choices=[('GERAL', 'Geral'), ('PRODUTOS', 'Produtos / Lançamentos'), ('TORNEIOS', 'Torneios'), ('EVENTOS', 'Eventos na Loja')], default='GERAL', max_length=20)),
                ('jogo', models.CharField(blank=True, help_text='Opcional: Digimon, Lorcana, Union Arena, etc.', max_length=50)),
                ('publicado', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, help_text='Se marcado, aparece em destaque no topo da lista.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
    ]
