# Generated by Django 6.0 on 2025-12-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='URL de uma imagem para ilustrar a notícia (usada na home/listas).'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Se marcado, aparece em destaque no topo / na home.'),
        ),
    ]
