# Generated by Django 6.0 on 2025-12-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newspost_imagem_url_alter_newspost_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='newspost',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem para ilustrar a notícia (aparece na home e na lista).', null=True, upload_to='news/'),
        ),
    ]
