# Generated by Django 6.0 on 2025-12-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_story',
            field=models.BooleanField(default=False, help_text='Se marcado, aparece na faixa de Stories da home.'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem para ilustrar a notícia (aparece na home, lista e stories).', null=True, upload_to='news/'),
        ),
    ]
