# Generated by Django 6.0 on 2025-12-29 04:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newspost_is_story_alter_newspost_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_opt_in',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_news_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.avatar_upload_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bandai_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_digimon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_lorcana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_union',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_ranking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
