# Generated by Django 6.0 on 2025-12-31 21:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_newspost_remove_userprofile_newsletter_opt_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_news_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bandai_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_digimon',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_lorcana',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_union',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='public_ranking',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tier',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nick de jogador'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_news',
            field=models.BooleanField(default=True, verbose_name='Quero receber novidades da Brickado por e-mail.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
