# Generated by Django 6.0 on 2025-12-27 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('TORNEIO', 'Torneio'), ('BONUS', 'Bônus'), ('CHECKIN', 'Check-in')], max_length=20)),
                ('pontos', models.IntegerField(help_text='Use valores positivos ou negativos')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
