# Generated by Django 6.0 on 2026-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_reward_rewardredemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardredemption',
            name='concluido',
            field=models.BooleanField(default=True),
        ),
    ]
