# Generated by Django 6.0 on 2025-12-28 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do torneio')),
                ('game', models.CharField(choices=[('DIGIMON', 'Digimon'), ('LORCANA', 'Lorcana'), ('UNION', 'Union Arena'), ('OUTRO', 'Outro')], default='DIGIMON', max_length=20, verbose_name='Jogo')),
                ('date', models.DateField(verbose_name='Data do torneio')),
                ('source', models.CharField(choices=[('INTERNAL', 'Rodado na Brickado Hub'), ('BANDAI', 'Bandai TCG+'), ('OTHER', 'Outro sistema')], default='INTERNAL', help_text='Se veio do Bandai TCG+ ou foi rodado dentro da Brickado Hub.', max_length=20, verbose_name='Origem')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_ranked', models.BooleanField(default=True, verbose_name='Conta para ranking da loja?')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='Nome que aparece no ranking da loja.', max_length=100, verbose_name='Nome do jogador')),
                ('bandai_id', models.CharField(blank=True, help_text='Opcional: ID usado no Bandai TCG+.', max_length=50, verbose_name='ID Bandai / TCG+')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Vitórias')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Derrotas')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Empates')),
                ('match_points', models.IntegerField(default=0, help_text='Ex: 3 por vitória, 1 por empate.', verbose_name='Pontos de partida')),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Colocação final')),
                ('buchholz', models.FloatField(blank=True, help_text='Opcional: força de oponentes (se quiser controlar).', null=True, verbose_name='Buchholz / SOS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['final_rank', '-match_points', 'player_name'],
            },
        ),
    ]
