# Generated by Django 6.0 on 2025-12-28 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deckcard_image_url'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allow_self_registration',
            field=models.BooleanField(default=True, verbose_name='Permitir inscrição pelo app?'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_points',
            field=models.IntegerField(default=1, verbose_name='Pontos por empate'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('SWISS', 'Suíço'), ('SINGLE', 'Mata-mata'), ('MIXED', 'Suíço + Top Cut')], default='SWISS', max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='loss_points',
            field=models.IntegerField(default=0, verbose_name='Pontos por derrota'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo de jogadores'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_1',
            field=models.CharField(choices=[('POINTS', 'Pontos de partida'), ('WINS', 'Número de vitórias'), ('BUCHHOLZ', 'Buchholz / SOS'), ('NAME', 'Nome do jogador (A-Z)')], default='POINTS', max_length=20, verbose_name='1º critério de desempate'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_2',
            field=models.CharField(choices=[('POINTS', 'Pontos de partida'), ('WINS', 'Número de vitórias'), ('BUCHHOLZ', 'Buchholz / SOS'), ('NAME', 'Nome do jogador (A-Z)')], default='BUCHHOLZ', max_length=20, verbose_name='2º critério de desempate'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_3',
            field=models.CharField(choices=[('POINTS', 'Pontos de partida'), ('WINS', 'Número de vitórias'), ('BUCHHOLZ', 'Buchholz / SOS'), ('NAME', 'Nome do jogador (A-Z)')], default='WINS', max_length=20, verbose_name='3º critério de desempate'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_4',
            field=models.CharField(choices=[('POINTS', 'Pontos de partida'), ('WINS', 'Número de vitórias'), ('BUCHHOLZ', 'Buchholz / SOS'), ('NAME', 'Nome do jogador (A-Z)')], default='NAME', max_length=20, verbose_name='4º critério de desempate'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='win_points',
            field=models.IntegerField(default=3, verbose_name='Pontos por vitória'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='deck',
            field=models.ForeignKey(blank=True, help_text='Deck cadastrado na Brickado Hub usado neste torneio (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_results', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='match_points',
            field=models.IntegerField(default=0, help_text='Ex: 3 por vitória, 1 por empate. Pode ser calculado a partir do critério do torneio.', verbose_name='Pontos de partida'),
        ),
    ]
