# Generated by Django 6.0 on 2025-12-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_allow_self_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentresult',
            name='buchholz',
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='omw',
            field=models.FloatField(blank=True, help_text='Taxa média de vitória dos oponentes. Pode ser copiado do resultado oficial Bandai.', null=True, verbose_name="OMW% (Opponents' Match Win Rate)"),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='oomw',
            field=models.FloatField(blank=True, help_text='Taxa média de vitória dos oponentes dos seus oponentes.', null=True, verbose_name="OOMW% (Opponents' Opponents' Match Win Rate)"),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tiebreaker_1',
            field=models.CharField(choices=[('POINTS', 'Match Points (total de pontos)'), ('OMW', "OMW% (Opponents' Match Win Rate)"), ('OOMW', "OOMW% (Opponents' Opponents' Match Win Rate)"), ('WINS', 'Número de vitórias'), ('NAME', 'Nome do jogador (A-Z)')], default='POINTS', max_length=20, verbose_name='1º critério de desempate'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tiebreaker_2',
            field=models.CharField(choices=[('POINTS', 'Match Points (total de pontos)'), ('OMW', "OMW% (Opponents' Match Win Rate)"), ('OOMW', "OOMW% (Opponents' Opponents' Match Win Rate)"), ('WINS', 'Número de vitórias'), ('NAME', 'Nome do jogador (A-Z)')], default='OMW', max_length=20, verbose_name='2º critério de desempate'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tiebreaker_3',
            field=models.CharField(choices=[('POINTS', 'Match Points (total de pontos)'), ('OMW', "OMW% (Opponents' Match Win Rate)"), ('OOMW', "OOMW% (Opponents' Opponents' Match Win Rate)"), ('WINS', 'Número de vitórias'), ('NAME', 'Nome do jogador (A-Z)')], default='OOMW', max_length=20, verbose_name='3º critério de desempate'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tiebreaker_4',
            field=models.CharField(choices=[('POINTS', 'Match Points (total de pontos)'), ('OMW', "OMW% (Opponents' Match Win Rate)"), ('OOMW', "OOMW% (Opponents' Opponents' Match Win Rate)"), ('WINS', 'Número de vitórias'), ('NAME', 'Nome do jogador (A-Z)')], default='WINS', max_length=20, verbose_name='4º critério de desempate'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='match_points',
            field=models.IntegerField(default=0, help_text='Ex: 3 por vitória, 1 por empate. Deve refletir a pontuação configurada no torneio.', verbose_name='Pontos de partida'),
        ),
    ]
