# Generated by Django 6.0 on 2025-12-28 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournamentresult_buchholz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.PositiveIntegerField(default=0, help_text='0 significa que ainda não começou.', verbose_name='Rodada atual'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_closed',
            field=models.BooleanField(default=False, verbose_name='Inscrições encerradas?'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('REG', 'Inscrições'), ('RUN', 'Em andamento'), ('DONE', 'Encerrado')], default='REG', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_rounds',
            field=models.PositiveIntegerField(default=0, verbose_name='Número total de rodadas'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='omw',
            field=models.FloatField(blank=True, help_text='Taxa média de vitória dos oponentes. Pode ser copiada do resultado oficial Bandai.', null=True, verbose_name="OMW% (Opponents' Match Win Rate)"),
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Rodada #')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Início da rodada')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Rodada encerrada?')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('tournament', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(verbose_name='Mesa #')),
                ('score_p1', models.PositiveIntegerField(default=0, verbose_name='Games do jogador 1')),
                ('score_p2', models.PositiveIntegerField(default=0, verbose_name='Games do jogador 2')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUBMITTED', 'Aguardando confirmação'), ('CONFIRMED', 'Confirmada'), ('DISPUTED', 'Em disputa (admin)')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='tournaments.tournamentresult')),
                ('player2', models.ForeignKey(blank=True, help_text='Se vazio, é BYE (vitória automática do player1).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='tournaments.tournamentresult')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_matches', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentround')),
            ],
            options={
                'ordering': ['round__number', 'table_number'],
            },
        ),
    ]
