# Generated by Django 6.0 on 2025-12-28 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_current_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da temporada')),
                ('slug', models.SlugField(help_text='Identificador na URL, ex: 2025-loja', max_length=100, unique=True, verbose_name='Slug')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Fim')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='deck_archetype_key',
            field=models.CharField(blank=True, help_text='Algo estável, ex: código da carta que define o deck.', max_length=100, verbose_name='Chave do deck (ex: ID da carta principal)'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='deck_archetype_name',
            field=models.CharField(blank=True, help_text="Nome do deck, ex: 'Aldamon Red Hybrid'.", max_length=150, verbose_name='Nome do deck / arquétipo'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournaments.season', verbose_name='Temporada'),
        ),
    ]
