# Generated by Django 6.0 on 2025-12-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deckcard_image_url'),
        ('tournaments', '0005_season_tournamentresult_deck_archetype_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='tournaments.tournamentresult'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Rodado na Brickado Hub'), ('BANDAI', 'Bandai TCG+'), ('OTHER', 'Outro sistema')], default='INTERNAL', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='bandai_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Bandai / TCG+'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_results', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='deck_archetype_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chave do deck (ex: ID da carta principal)'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='deck_archetype_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do deck / arquétipo'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='match_points',
            field=models.IntegerField(default=0, verbose_name='Pontos de partida'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='omw',
            field=models.FloatField(blank=True, null=True, verbose_name='OMW%'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='oomw',
            field=models.FloatField(blank=True, null=True, verbose_name='OOMW%'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='player_name',
            field=models.CharField(max_length=100, verbose_name='Nome do jogador'),
        ),
    ]
