# Generated by Django 6.0 on 2025-12-28 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_match_player2_alter_tournament_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round', 'table_number']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tournamentresult',
            options={'ordering': ['tournament', 'final_rank', 'player_name']},
        ),
        migrations.AlterModelOptions(
            name='tournamentround',
            options={'ordering': ['tournament', 'number']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tiebreaker_1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tiebreaker_2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tiebreaker_3',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tiebreaker_4',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='deck_archetype_key',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='extra_time_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='games_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='games_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='extra_time_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando resultado'), ('SUBMITTED', 'Resultado enviado'), ('CONFIRMED', 'Confirmado'), ('DISPUTED', 'Em disputa')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='table_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=True, help_text='Temporada ativa para rankings e novos torneios.'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='allow_self_registration',
            field=models.BooleanField(default=True, help_text='Permitir que o jogador se registre pelo app.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='current_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='draw_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('SWISS', 'Suíço'), ('SE', 'Single Elimination')], default='SWISS', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('DIGIMON', 'Digimon'), ('LORCANA', 'Lorcana'), ('UNION', 'Union Arena')], default='DIGIMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_ranked',
            field=models.BooleanField(default=True, help_text='Se marcado, conta para o ranking geral / da temporada.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='loss_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournaments.season'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='source',
            field=models.CharField(choices=[('HUB', 'Rodado na Brickado Hub'), ('BANDAI_APP', 'Registrado via Bandai TCG+'), ('OTHER', 'Outro sistema')], default='HUB', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('REG', 'Inscrições'), ('RUN', 'Em andamento'), ('DONE', 'Encerrado')], default='REG', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_rounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='win_points',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='bandai_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='deck_archetype_name',
            field=models.CharField(blank=True, help_text="Nome do arquétipo, ex: 'Agumon Bond', 'AlphaMon', etc.", max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='match_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='omw',
            field=models.FloatField(blank=True, help_text="Opponents' Match Win %", null=True),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='oomw',
            field=models.FloatField(blank=True, help_text="Opponents' Opponents' Match Win %", null=True),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='player_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
