# Generated by Django 6.0 on 2025-12-29 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deckcard_image_url'),
        ('tournaments', '0007_alter_match_options_alter_season_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentresult',
            options={'ordering': ['tournament', 'player_name']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='allow_self_registration',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='draw_points',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='extra_time_minutes',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='loss_points',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='source',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='win_points',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='dropped',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='games_lost',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='games_won',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='oomw',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='extra_time_minutes',
        ),
        migrations.RemoveField(
            model_name='tournamentround',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='origin',
            field=models.CharField(choices=[('HUB', 'Rodado na Brickado Hub'), ('BANDAI', 'Rodado em app oficial')], default='HUB', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='oowm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SUBMITTED', 'Enviado'), ('CONFIRMED', 'Confirmado'), ('DISPUTED', 'Em disputa')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('SWISS', 'Suíço'), ('ELIM', 'Eliminação simples')], default='SWISS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_ranked',
            field=models.BooleanField(default=True, help_text='Se marcado, resultados contam para o ranking da temporada.'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_uses', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='deck_archetype_name',
            field=models.CharField(blank=True, help_text='Nome livre do arquétipo do deck (ex: Greymon, Jesmon, etc.).', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='omw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
