# Generated by Django 6.0 on 2025-12-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournamentresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament', 'round', 'table_number']},
        ),
    ]
