# Generated by Django 6.0 on 2026-01-03 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0003_remove_deckcard_image_url_deckcard_card"),
        ("tournaments", "0009_alter_match_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentresult",
            name="deck",
        ),
        migrations.RemoveField(
            model_name="tournamentresult",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="tournamentresult",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="tournamentround",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tournamentround",
            name="tournament",
        ),
        migrations.AlterModelOptions(
            name="tournament",
            options={},
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="current_round",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="format",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="is_ranked",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="registration_closed",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="total_rounds",
        ),
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="active",
            field=models.BooleanField(default=True),
        ),

        # ✅ CORREÇÃO AQUI: default=1 é inválido para DateField
        # Usando uma data fixa para preencher registros antigos (pode ser qualquer data válida)
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateField(default=datetime.date(2026, 1, 3)),
            preserve_default=False,
        ),

        # ✅ CORREÇÃO AQUI: removida a vírgula errada após AlterField(
        migrations.AlterField(
            model_name="season",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),

        migrations.AlterField(
            model_name="tournament",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="game",
            field=models.CharField(
                choices=[
                    ("DIGIMON", "Digimon"),
                    ("LORCANA", "Lorcana"),
                    ("UNION", "Union Arena"),
                    ("OUTRO", "Outro TCG"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Inscrições ativas"),
                    ("RUNNING", "Em andamento"),
                    ("FINISHED", "Finalizado"),
                ],
                default="REGISTRATION",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("player_name", models.CharField(max_length=120)),
                ("deck_archtype_name", models.CharField(blank=True, max_length=120)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("omw", models.FloatField(default=0.0, help_text="Opponents' Match Win %")),
                ("oomw", models.FloatField(default=0.0, help_text="Opponents' Opponents' Match Win %")),
                ("deck", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="decks.deck")),
                ("tournament", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="players", to="tournaments.tournament")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-points", "-omw", "-oomw"],
                "unique_together": {("tournament", "player_name")},
            },
        ),
        migrations.DeleteModel(
            name="Match",
        ),
        migrations.DeleteModel(
            name="TournamentResult",
        ),
        migrations.DeleteModel(
            name="TournamentRound",
        ),
    ]
