# Generated by Django 6.0 on 2025-12-27 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogo', models.CharField(choices=[('DIGIMON', 'Digimon'), ('LORCANA', 'Lorcana'), ('UNION', 'Union Arena')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('publico', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_carta', models.CharField(max_length=120)),
                ('codigo_carta', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='decks.deck')),
            ],
        ),
    ]
