# Generated by Django 6.0 on 2025-12-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
