# Generated by Django 6.0 on 2026-01-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_digimoncard_api_id_alter_digimoncard_attribute_and_more'),
        ('decks', '0002_deckcard_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='image_url',
        ),
        migrations.AddField(
            model_name='deckcard',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.digimoncard'),
        ),
    ]
