# Generated by Django 6.0 on 2026-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_remove_deckcard_image_url_deckcard_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='arquetipo',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
