# Generated by Django 6.0 on 2026-01-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_deck_arquetipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='jogo',
            field=models.CharField(choices=[('DIGIMON', 'Digimon'), ('LORCANA', 'Lorcana'), ('UNION', 'Union Arena')], default='DIGIMON', max_length=20),
        ),
    ]
