# Generated by Django 6.0 on 2026-01-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_banlistrule_cardcopyrule_pairbanrule_and_more'),
        ('decks', '0005_alter_deck_jogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('-criado_em',)},
        ),
        migrations.AlterModelOptions(
            name='deckcard',
            options={'ordering': ('section', 'id')},
        ),
        migrations.AddField(
            model_name='deckcard',
            name='section',
            field=models.CharField(choices=[('MAIN', 'Main Deck'), ('EGG', 'Digi-Egg Deck')], db_index=True, default='MAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='deck',
            name='arquetipo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='deck',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deck',
            name='jogo',
            field=models.CharField(choices=[('DIGIMON', 'Digimon')], default='DIGIMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_decks', to='cards.digimoncard'),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='codigo_carta',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='nome_carta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='deckcard',
            index=models.Index(fields=['deck', 'section'], name='decks_deckc_deck_id_728008_idx'),
        ),
        migrations.AddIndex(
            model_name='deckcard',
            index=models.Index(fields=['deck', 'codigo_carta'], name='decks_deckc_deck_id_1006c4_idx'),
        ),
        migrations.AddIndex(
            model_name='deckcard',
            index=models.Index(fields=['deck', 'card'], name='decks_deckc_deck_id_f8adda_idx'),
        ),
    ]
