# Generated by Django 6.0 on 2026-01-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_alter_deck_options_alter_deckcard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=140, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='arquetipo_nome',
            field=models.CharField(blank=True, default='', help_text="Nome livre do arquétipo (ex.: 'BLL AncientGreymon').", max_length=120),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='arquetipo',
            field=models.ForeignKey(blank=True, help_text='Arquetipo principal (opcional, gerenciado via Admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='decks.archetype'),
        ),
    ]
