# Generated by Django 6.0 on 2025-12-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimoncard',
            name='api_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
