# Generated by Django 6.0 on 2026-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_digimoncard_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimoncard',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='attribute',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='digitype',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='type',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
