# Generated by Django 6.0 on 2026-01-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_digimoncard_api_id_alter_digimoncard_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=180)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_url', models.URLField(blank=True, default='')),
                ('in_stock', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cardnumber'],
            },
        ),
    ]
