# Generated by Django 6.0 on 2026-01-04 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardprice',
            options={'ordering': ('cardnumber',)},
        ),
        migrations.AlterModelOptions(
            name='digimoncard',
            options={'ordering': ('cardnumber',)},
        ),
        migrations.RemoveField(
            model_name='digimoncard',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='digimoncard',
            name='type',
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='card_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='dp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='evo_color_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='evo_color_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='evo_cost_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='evo_cost_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='inherit_effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='last_synced_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='pack',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='play_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='rarity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='security_effect',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='cardnumber',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='attribute',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='cardnumber',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='digitype',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
