# Generated by Django 6.0 on 2026-01-04 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardprice_options_alter_digimoncard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprice',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
