# Generated by Django 6.0 on 2026-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cardprice_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='digimoncard',
            name='color2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='digitype2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='evo_level_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='evo_level_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='form',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
