# Generated by Django 6.0 on 2026-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_digimoncard_color2_digimoncard_digitype2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanlistRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('BANNED', 'Banida (0)'), ('LIMITED_1', 'Limitada a 1'), ('LIMITED_2', 'Limitada a 2'), ('LIMITED_3', 'Limitada a 3')], default='BANNED', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('cardnumber',),
            },
        ),
        migrations.CreateModel(
            name='CardCopyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(db_index=True, max_length=32, unique=True)),
                ('max_copies', models.PositiveIntegerField(default=4)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('cardnumber',),
            },
        ),
        migrations.CreateModel(
            name='PairBanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_a', models.CharField(db_index=True, max_length=32)),
                ('card_b', models.CharField(db_index=True, max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('card_a', 'card_b'),
            },
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='product_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='attribute',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='card_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='color',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='color2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='digitype',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='digitype2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='dp',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='effect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='evo_color_1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='evo_color_2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='form',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='inherit_effect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='level',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='pack',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='play_cost',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='rarity',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='digimoncard',
            name='security_effect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['name'], name='cards_digim_name_ed18a7_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['cardnumber'], name='cards_digim_cardnum_1e7e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['card_type'], name='cards_digim_card_ty_6f583f_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['color'], name='cards_digim_color_de99fa_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['level'], name='cards_digim_level_203da0_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['play_cost'], name='cards_digim_play_co_21f7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['dp'], name='cards_digim_dp_cbbcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['attribute'], name='cards_digim_attribu_a37880_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['digitype'], name='cards_digim_digityp_38ee3a_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncard',
            index=models.Index(fields=['rarity'], name='cards_digim_rarity_e206ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='pairbanrule',
            constraint=models.UniqueConstraint(fields=('card_a', 'card_b'), name='uniq_pairban_a_b'),
        ),
    ]
